
export enum UserType {
  EMPLOYEE = 'Employee',
  BUSINESS = 'Business',
  STUDENT = 'Student'
}

export enum ExpenseCategory {
  RENT = 'Rent',
  FOOD = 'Food',
  TRAVEL = 'Travel',
  UTILITIES = 'Utilities',
  EDUCATION = 'Education',
  MEDICAL = 'Medical',
  BUSINESS_COSTS = 'Business Costs',
  BUSINESS_RESERVATION = 'Business Reservation',
  PROVISIONS = 'Provisions',
  TAX_RESERVE = 'Tax Reserve',
  ENTERTAINMENT = 'Entertainment',
  ATM_WITHDRAWAL = 'ATM Withdrawal',
  OTHER = 'Other'
}

export enum IncomeSourceType {
  SALARY = 'Salary',
  BUSINESS_PROFIT = 'Business Profit',
  FREELANCING = 'Freelancing',
  PART_TIME = 'Part-time',
  OTHER = 'Other'
}

export interface IncomeSource {
  id: string;
  type: IncomeSourceType;
  amount: number;
  date: string;
  note: string;
}

export interface ItemizedExpense {
  name: string;
  amount: number;
  category: string;
}

export interface Expense {
  id: string;
  category: ExpenseCategory;
  subCategory?: string;
  amount: number;
  date: string;
  note: string;
  isAutoGenerated?: boolean;
  isCash?: boolean;
  linkedBank?: string;
  items?: ItemizedExpense[];
}

export interface Debt {
  id: string;
  name: string;
  balance: number;
  interestRate: number;
  minimumPayment: number;
}

export interface Goal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  category: string;
  deadline?: string;
}

export interface AllocationPercentages {
  essentials: number;
  savings: number;
  investments: number;
  emergency: number;
  goals: number;
}

export type RecurringFrequency = 'Daily' | 'Weekly' | 'Monthly' | 'Quarterly' | 'Half-Yearly' | 'Yearly';

export interface RecurringExpense {
  id: string;
  name: string;
  amount: number;
  category: ExpenseCategory;
  frequency: RecurringFrequency;
  startDate: string;
  lastProcessedDate: string;
}

/**
 * Independent data container for each profile type
 */
export interface ProfileData {
  incomeSources: IncomeSource[];
  expenses: Expense[];
  goals: Goal[];
  debts?: Debt[];
  allocation: AllocationPercentages;
  monthlyLimit: number;
  categoryBudgets?: Record<string, number>;
  reconciledCashBalance?: number;
  recurringExpenses?: RecurringExpense[];
  recurringSetupComplete?: boolean;
}

export interface AppState {
  userType: UserType | null;
  profiles: Record<UserType, ProfileData>;
  currency: string;
  onboarded: boolean;
}
