import { ProfileData, Expense, Debt } from '../types';

export const calculateHealthScore = (profile: ProfileData): number => {
    let score = 500; // Base score

    const totalIncome = profile.incomeSources.reduce((sum, inc) => sum + inc.amount, 0);
    const totalExpenses = profile.expenses.reduce((sum, e) => sum + e.amount, 0);
    const hasIncome = totalIncome > 0;

    // Rule 1: Operating Profitability (Most Important)
    if (hasIncome) {
        if (totalExpenses > totalIncome) {
            // Deficit spending penalty
            score -= 300;
        } else {
            // Positive savings rate
            const savingsRate = (totalIncome - totalExpenses) / totalIncome;
            if (savingsRate > 0.4) score += 200;
            else if (savingsRate > 0.2) score += 100;
            else if (savingsRate > 0.05) score += 50;
        }
    } else if (totalExpenses > 0) {
        // Spending without income
        score -= 200;
    }

    // Rule 2: Spending within explicitly set budget limit
    if (profile.monthlyLimit > 0) {
        if (totalExpenses > profile.monthlyLimit) score -= 150; // Over budget
        else if (totalExpenses < profile.monthlyLimit * 0.8) score += 100; // 20% under budget
    }

    // Rule 3: Goals progress
    const goalsTotal = profile.goals.reduce((sum, g) => sum + g.currentAmount, 0);
    const goalsTarget = profile.goals.reduce((sum, g) => sum + g.targetAmount, 0);
    if (goalsTarget > 0 && (goalsTotal / goalsTarget) > 0.1) score += 100;
    if (goalsTarget > 0 && (goalsTotal / goalsTarget) > 0.5) score += 100;

    // Rule 4: Debt penalty
    if (profile.debts && profile.debts.length > 0) {
        const totalDebt = profile.debts.reduce((sum, d) => sum + d.balance, 0);
        if (totalDebt > 10000) score -= 100;
    }

    return Math.min(Math.max(score, 0), 1000);
};

export const detectSubscriptions = (expenses: Expense[]): { amount: number, name: string, count: number }[] => {
    const grouped = expenses.reduce((acc, curr) => {
        if (curr.isAutoGenerated) return acc;

        // Only detect if it's the exact same amount and exact same note, for simplicity
        const key = `${curr.amount}-${curr.note.toLowerCase().trim()}`;
        if (!acc[key]) acc[key] = { amount: curr.amount, name: curr.note, count: 0 };
        acc[key].count++;
        return acc;
    }, {} as Record<string, { amount: number, name: string, count: number }>);

    return Object.values(grouped).filter(g => g.count >= 2);
};

export const calculatePayoffStrategy = (debts: Debt[], strategy: 'avalanche' | 'snowball'): Debt[] => {
    const sorted = [...debts];
    if (strategy === 'avalanche') {
        sorted.sort((a, b) => b.interestRate - a.interestRate);
    } else {
        // snowball
        sorted.sort((a, b) => a.balance - b.balance);
    }
    return sorted;
};

export const detectLifestyleInflation = (expenses: Expense[]): boolean => {
    // Dynamic heuristic: if non-essential spending exceeds 30% of total expenses and is over a baseline
    const nonEssentialCats = ['Entertainment', 'Travel', 'Other'];

    const totalExpenses = expenses.reduce((s, e) => s + e.amount, 0);
    if (totalExpenses === 0) return false;

    const discretionaryTotal = expenses
        .filter(e => nonEssentialCats.includes(e.category))
        .reduce((s, e) => s + e.amount, 0);

    // Trigger alert if discretionary goes above 30% of total AND is more than $200 absolute
    return (discretionaryTotal / totalExpenses) > 0.3 && discretionaryTotal > 200;
};

export const processRoutineExpenses = (profile: ProfileData): { generatedExpenses: Expense[], updatedRecurring: NonNullable<ProfileData['recurringExpenses']> } => {
    if (!profile.recurringExpenses || profile.recurringExpenses.length === 0) return { generatedExpenses: [], updatedRecurring: [] };

    const generatedExpenses: Expense[] = [];
    const updatedRecurring = JSON.parse(JSON.stringify(profile.recurringExpenses)) as NonNullable<ProfileData['recurringExpenses']>;

    const now = new Date();

    for (let i = 0; i < updatedRecurring.length; i++) {
        const recurring = updatedRecurring[i];
        let lastDate = new Date(recurring.lastProcessedDate);
        const advanceDate = (d: Date, freq: string) => {
            const next = new Date(d);
            if (freq === 'Daily') next.setDate(next.getDate() + 1);
            else if (freq === 'Weekly') next.setDate(next.getDate() + 7);
            else if (freq === 'Monthly') next.setMonth(next.getMonth() + 1);
            else if (freq === 'Quarterly') next.setMonth(next.getMonth() + 3);
            else if (freq === 'Half-Yearly') next.setMonth(next.getMonth() + 6);
            else if (freq === 'Yearly') next.setFullYear(next.getFullYear() + 1);
            return next;
        };

        let nextDueDate = advanceDate(lastDate, recurring.frequency);

        // Use a safety break to prevent infinite loops from bad dates
        let failsafe = 0;
        while (nextDueDate <= now && failsafe < 500) {
            failsafe++;
            generatedExpenses.push({
                id: Math.random().toString(36).substr(2, 9),
                category: recurring.category,
                amount: recurring.amount,
                date: nextDueDate.toISOString(),
                note: recurring.name,
                isAutoGenerated: true
            });
            lastDate = nextDueDate;
            nextDueDate = advanceDate(lastDate, recurring.frequency);
        }

        updatedRecurring[i].lastProcessedDate = lastDate.toISOString();
    }

    return { generatedExpenses, updatedRecurring };
};
